# Start with the Node 20.8 image
FROM node:20.8

# Set the working directory in the Docker container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install Svelte project dependencies
RUN npm install

# Bundle app source
COPY . .

# Build the Svelte app
RUN npm run build

RUN npm install -g serve

# Make port 5000 available to the world outside this container
EXPOSE 8080

# Define the command to serve the Svelte app
CMD ["serve", "-s", "build", "-l", "8080"]
