# Start from the Python 3.11.5 slim image
FROM python:3.11.5-slim

# Set the working directory in the container
WORKDIR /app

# Install gcc and python3-dev
RUN apt-get update && apt-get install -y gcc python3-dev

# Install requirements
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application
COPY . .

# Expose the port your app runs on
EXPOSE 5000

# Define the command to run your app (adjust as necessary)
CMD ["python", "app.py"]
